### ISSUE TITLE
Entrega 2 e 3 

### ISSUE THREAD

**Issue by lucascunhaiftm** [zBornConfused/trabalhoppw.io#2]
No Github, a branch master não existe, ela foi excluída?
Deve ser feito o merge na master. Eram duas entregas em duas branch diferentes.
No site, as customizações estão incompletas, tente melhorá-las usando dimensões, estilização de textos.
Nas imagens das lojas combine, o link <a> com imagens dentro, use css para diminuir as imagens.
As imagens dos jogos devem ficar como no exemplo, alinhadas no centro e com tamanho maior. Use margin para centralizá-las

**Comment by zBornConfused** [comment]
Lucas, eu to com um problemão cara. Eu fui tentar fazer o merge, acabei confundindo e fiz o upload do branch 3 e não faço ideia de como reverter. Eu fiz os commits mas parece que não consigo reverter e voltar pra versão final

**Comment by lucascunhaiftm** [comment]
Não sei se entendi direito a situação, mas vou te dar umas dicas aqui:
Toda vez que você commita é como se vc fizesse uma cópia dos arquivos. 
Para listar todos os commits: git log
Caso você queira voltar em algumas dessas cópias, ou seja, voltar na versão exata dos arquivos: git checkout hash_do_commit (aquela hash que cada commit tem)
Temos tbm um comando que faz com que volte até um determinado commit, mas ele acaba apagando os commits depois dele : git revert hash_do_commit.
Segue um link para esses comandos: https://brorlandi.github.io/git-desfazendo-commits

**Comment by zBornConfused** [comment]
Pode conferir pra mim se o trabalho ta tudo ok? Parece que sem querer eu peguei os arquivos da branch 3 e coloquei na branch 4, e isso acabou substituindo os arquivos das paginas dos jogos.

**Comment by zBornConfused** [comment]
Outro detalhe é que eu uso o github desktop, eu não tenho o linux aqui no meu pc
